#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Usage: $0 <Debug|Release> [...]"
    exit 1
fi

mode=$1

if [[ ! $mode =~ Debug|Release ]]
then
    echo "Invalid mode $mode, please select either Debug or Release"
    exit 1
fi

prefix=out/$mode

if [ ! -d $prefix ]
then
    echo "Project not configured, please run ./scripts/configure first"
    exit 1
fi

cmake --build $prefix "${@:2}"
